version: "3.8"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php_code/:/var/www/html/
      - ./certs:/etc/nginx/ssl

  php:
    build:
      context: ./php_code/
    expose:
      - "9000"
    volumes:
      - ./php_code/:/var/www/html/



  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./php:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --register-unsafely-without-email --agree-tos --no-eff-email --force-renewal -d adjms.sof60.dk
    depends_on:
      - nginx

  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Dboa24!!
    volumes:
      - /C/DB:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mariadb
